spring.datasource.driver-class-name=org.sqlite.JDBC
spring.datasource.url=jdbc:sqlite:/home/ga/ga/GitHub/Eval-Glpi/test-sqlite/boutique.db
spring.datasource.username=
spring.datasource.password=

# Utilisation de la classe fournie par la nouvelle dépendance hibernate-community-dialects
spring.jpa.properties.hibernate.dialect=org.hibernate.community.dialect.SQLiteDialect

# Empêche Hibernate 7 de chercher des métadonnées complexes non gérées par SQLite au boot
spring.jpa.properties.hibernate.temp.use_jdbc_metadata_defaults=false

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true